"""Render a kit to SFZ — the open, text-based sampler format.

SFZ is a deliberately dumb target: one ``<region>`` per piece, each mapped to
its ``playback.root_key``. Pieces that share a key are emitted as round-robins
(``seq_length`` / ``seq_position``) so a repeated note cycles through them, the
way a real kit's multiple snare samples would. Everything expressive that SFZ
*can't* say (prompt, provenance, features) simply isn't here — it lives in
``kit.yaml``.
"""

from __future__ import annotations

import os
from collections import defaultdict

from ..model import Kit


def render_sfz(kit: Kit, sample_dir: str = "samples") -> str:
    """Return the text of an ``.sfz`` file for ``kit``.

    ``sample_dir`` is written as the SFZ ``default_path`` (relative to the .sfz
    file), so ``sample=`` opcodes carry only the bare filename.
    """
    lines: list[str] = [
        f"// {kit.name} — generated by drumkitgen",
    ]
    if kit.prompt:
        lines.append(f"// prompt: {kit.prompt}")
    lines += [
        "// canonical metadata: kit.yaml",
        "",
        "<control>",
        f"default_path={sample_dir}/",
        "",
        "<global>",
        "ampeg_attack=0.001",
        "loop_mode=one_shot",
        "",
    ]

    by_key: dict[int, list] = defaultdict(list)
    for piece in kit.pieces:
        by_key[piece.playback.root_key].append(piece)

    for key in sorted(by_key):
        group = by_key[key]
        round_robin = len(group) > 1
        for i, piece in enumerate(group, start=1):
            filename = os.path.basename(piece.file)
            lines.append(f"<region> // {piece.id} [{piece.slot.value}]")
            lines.append(f"sample={filename}")
            lines.append(f"key={key}")
            lines.append(f"pitch_keycenter={key}")
            if piece.playback.tune_cents:
                lines.append(f"tune={piece.playback.tune_cents}")
            if piece.playback.gain_db:
                lines.append(f"volume={piece.playback.gain_db:.2f}")
            if piece.playback.pan:
                lines.append(f"pan={piece.playback.pan:.2f}")
            if round_robin:
                lines.append(f"seq_length={len(group)}")
                lines.append(f"seq_position={i}")
            lines.append("")

    return "\n".join(lines)
